module.exports.productsData = [
    {
        "id": 1,
        "title": "Intelligent Rubber Computer",
        "description": "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
        "price": "138.00",
        "quantity": "$11.45",
        "image": "https://fickle-outback.net/",
    },
    {
        "id": 2,
        "title": "Intelligent Rubber Chair",
        "description": "The Football Is Good For Training And Recreational Purposes",
        "price": "800.00",
        "quantity": "$18.12",
        "image": "https://potable-postage.name",
    },
    {
        "id": 3,
        "title": "Handcrafted Frozen Shirt",
        "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
        "price": "242.00",
        "quantity": "$7.84",
        "image": "https://hopeful-assumption.org/",
        
    },
    {
        "id": 4,
        "title": "Luxurious Metal Ball",
        "description": "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
        "price": "783.00",
        "quantity": "$11.52",
        "image": "https://attached-item.com/",
    },
    {
        "id": 5,
        "title": "Practical Plastic Hat",
        "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
        "price": "263.00",
        "quantity": "$12.91",
        "image": "https://sleepy-center.org/",
    },
    {
        "id": 6,
        "title": "Bespoke Concrete Sausages",
        "description": "The Football Is Good For Training And Recreational Purposes",
        "price": "737.00",
        "quantity": "$6.68",
        "image": "https://roasted-shower.org",
    },
    {
        "id": 7,
        "title": "Sleek Concrete Soap",
        "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
        "price": "343.00",
        "quantity": "$4.06",
        "image": "https://plain-finance.name",
    },
    {
        "id": 8,
        "title": "Luxurious Concrete Car",
        "description": "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
        "price": "922.00",
        "quantity": "$12.41",
        "image": "https://raw-rebellion.biz",
    },
    {
        "id": 9,
        "title": "Intelligent Plastic Keyboard",
        "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
        "price": "736.00",
        "quantity": "$11.37",
        "image": "https://neglected-eye.biz",
    },
    {
        "id": 10,
        "title": "Refined Soft Tuna",
        "description": "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        "price": "319.00",
        "quantity": "$6.51",
        "image": "https://edible-sausage.name/",
    }
]